name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm install
    - name: production build
      run: npm run build
    - name: publish to npm
      env:
        CI: true
